apiVersion: v1
kind: Service
namespace: comin
metadata:
  name: comin-authentication-service
spec:
  selector:
    app: comin-authentication-service
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP